import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/3b2468ae5a.js"
          crossOrigin="anonymous"
        ></script>
        <script src="node_modules/@material-tailwind/html/scripts/collapse.js"></script>

        <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
